export { default as Navbar } from './layout/Navbar.vue'
export { default as Footer } from './layout/Footer.vue'
export { default as HeroSection } from './sections/HeroSection.vue'
export { default as FeaturedPatternsSection } from './sections/FeaturedPatternsSection.vue'
export { default as FeaturedStoriesSection } from './sections/FeaturedStoriesSection.vue'
export { default as CTASection } from './sections/CTASection.vue'
export { default as AiAvatar } from './AiAvatar.vue'
export { default as RibbonCanvas } from './RibbonCanvas.vue'
